openapi: 3.0.1
info:
  title: Countable Resource API
  description: Countable Resource RESTful WebService
  version: 1.0.0
servers:
  - url: http://localhost:8080/
tags:
  - name: countable-resources
    description: Countable Resources
paths:
  /countable-resources:
    post:
      tags:
        - countable-resource
      summary: Add a countable resource
      operationId: addCountableResource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountableResource'
        required: true
      responses:
        201:
          description: Created
          headers:
            ETag:
              description: Entity Tag to identify resource revsion.
              schema:
                type: object
          content: {}
        400:
          description: Bad Request
          content: {}
        409:
          description: Conflict - Name already exists
          content: {}
      x-codegen-request-body-name: body
  /countable-resources/{name}:
    get:
      tags:
        - countable-resource
      summary: Find countable resource by name
      description: Returns a single countable resource
      operationId: getCountableResourceByName
      parameters:
        - name: name
          in: path
          description: The name of the countable resource
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 20
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountableResource'
          headers:
            ETag:
              description: Entity Tag to identify resource revsion.
              schema:
                type: object
        400:
          description: Invalid name supplied
          content: {}
        404:
          description: Countable resource not found
          content: {}
    put:
      tags:
        - countable-resource
      summary: Update an existing countable resource
      operationId: updateCountableResource
      parameters:
        - name: name
          in: path
          description: The name of the countable resource
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 20
        - in: header
          name: If-Match
          schema:
            type: string
            format: int64
            description: ETag of the entity expected to update - will return 412 if it doesnt match ETag
          required: true
      requestBody:
        description: Countable resource object that needs to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountableResource'
        required: true
      responses:
        200:
          description: OK
          headers:
            ETag:
              description: Resource revision id
              schema:
                type: object
          content: {}
        400:
          description: Invalid name supplied
          content: {}
        404:
          description: Countable resource not found
          content: {}
        409:
          description: Conflict - Name already exists
          content: {}
        412:
          description: \'If-Match\' header did not match ETag
          content: {}
      x-codegen-request-body-name: body
components:
  schemas:
    CountableResource:
      required:
        - count
        - name
      type: object
      properties:
        name:
          minLength: 3
          maxLength: 20
          type: string
        count:
          type: integer
          format: int64
